<a href="https://colab.research.google.com/github/Rlackdals981010/NLP_STUDY_WITH_DL/blob/main/Text_Preprocessing_Splitting_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#모두가 알듯 지도 학습에서는 데이터를 train과 test로 분류 해야한다. (validation은 일단 제외)
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
# 1. zip 함수를 이용하여 분리하기
X,y = zip(['a',1],['b',2],['c',3])
print('X 데이터 :',X)
print('y 데이터 :',y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [4]:
sequence = [['a',1],['b',2],['c',3]]
X,y = zip(*sequence) #*을 통해서 a,b,c를 묶고 1,2,3을 묶는거임
print('X 데이터 :',X)
print('y 데이터 :',y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [7]:
# 2. df를 이용해서 분리하기
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]

columns = ['메일 본문','스펨 메일 유무']

df = pd.DataFrame(values,columns=columns)
df

메일 본문  스펨 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [9]:
X = df['메일 본문']
y = df['스펨 메일 유무']
print('X 데이터 :',X.to_list())
print('y 데이터 :',y.to_list())

X 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터 : [1, 0, 0, 1]


In [10]:
# 3. Numpy 이용
# 넘파이의 슬라이싱을 이용하여 데이터 분리
np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
X = np_array[:,:3]
y = np_array[:,3]

print('X 데이터 :')
print(X)
print('y 데이터 :',y)

X 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


In [12]:
#테스트 데이터 분리하기
#위처럼 target과 label을 분리했으면 테스트 데이터를 분리해야함

In [13]:
# 1. 사이킷 런 이용하기
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=1234) # test_size = 0.2 -> train_size =0.8

In [ ]:
# 2.수동 분리
# 는 안하겠음